### PR TITLE
Strip debug info from go binaries

### PR DESCRIPTION
**Pull request by zmackie**
- https://blog.filippo.io/shrink-your-go-binaries-with-this-one-weird-trick/

Signed-off-by: Zander Mackie <zmackie@gmail.com>

Thanks for contributing to the buildpack. To speed up the process of reviewing your pull request please provide us with:

* A short explanation of the proposed change:

- Adds ldflags that remove debug information ∴ shrinking binaries

* An explanation of the use cases your change solves

* [ ] I have viewed signed and have submitted the Contributor License Agreement

* [ ] I have made this pull request to the `develop` branch

* [ ] I have added an integration test

### CODE REVIEW

**Comment by zmackie** [comment]
I checked this and it reduces the size of the `testdata/vendored` app by 2megs. Not a lot, but it was roughly %20 shrink.

**Comment by joshzarrabi** [comment]
I rebased this on top of master to get the tests to run.

**Comment by ForestEckhardt** [comment]
@zmackie After getting the unit tests to pass, I failed at integration stage and there is little documentation I can find on how this should be structured. I am going to close the PR for now due to inactivity. If you would like to reopen with a fix that would be much appreciated. If this is something you would like the team to consider adding please feel free to open an issue.

**Comment by arjun024** [comment]
Looks like go install takes build flags as args. So linker flags have to passed as `-ldflags="-s -w"`

**Pull request closed without merging**
